const STATE_RANGE_CONFIG = {
  "A-F": ["A", "B", "C", "D", "F"],
  "G-K": ["G", "H", "I", "K"],
  "L-M": ["L", "M"],
  "N-P": ["N", "O", "P"],
  "S-W": ["Q", "R", "S", "T", "U", "V", "W"],
};

const stateData = [
  {
    code: "AL",
    name: "Alabama",
    grantAmount: 843050,
    townsAwarded: 17,
  },
  {
    code: "AK",
    name: "Alaska",
    grantAmount: 0,
    townsAwarded: 0,
  },
  {
    code: "AZ",
    name: "Arizona",
    grantAmount: 233785,
    townsAwarded: 5,
  },
  {
    code: "AR",
    name: "Arkansas",
    grantAmount: 341000,
    townsAwarded: 7,
  },
  {
    code: "CA",
    name: "California",
    grantAmount: 869416.54,
    townsAwarded: 18,
  },
  {
    code: "CO",
    name: "Colorado",
    grantAmount: 153000,
    townsAwarded: 4,
  },
  {
    code: "CT",
    name: "Connecticut",
    grantAmount: 124192,
    townsAwarded: 3,
  },
  {
    code: "DE",
    name: "Delaware",
    grantAmount: 79250,
    townsAwarded: 2,
  },
  {
    code: "DC",
    name: "District Of Columbia",
    grantAmount: 0,
    townsAwarded: 0,
  },
  {
    code: "FL",
    name: "Florida",
    grantAmount: 412723,
    townsAwarded: 9,
  },
  {
    code: "GA",
    name: "Georgia",
    grantAmount: 749174,
    townsAwarded: 15,
  },
  {
    code: "HI",
    name: "Hawaii",
    grantAmount: 50000,
    townsAwarded: 1,
  },
  {
    code: "ID",
    name: "Idaho",
    grantAmount: 308496,
    townsAwarded: 6,
  },
  {
    code: "IL",
    name: "Illinois",
    grantAmount: 846855.81,
    townsAwarded: 19,
  },
  {
    code: "IN",
    name: "Indiana",
    grantAmount: 474967.0,
    townsAwarded: 10,
  },
  {
    code: "IA",
    name: "Iowa",
    grantAmount: 655975.5,
    townsAwarded: 15,
  },
  {
    code: "KS",
    name: "Kansas",
    grantAmount: 623500,
    townsAwarded: 13,
  },
  {
    code: "KY",
    name: "Kentucky",
    grantAmount: 452148.3,
    townsAwarded: 10,
  },
  {
    code: "LA",
    name: "Louisiana",
    grantAmount: 250000.0,
    townsAwarded: 5,
  },
  {
    code: "ME",
    name: "Maine",
    grantAmount: 526072,
    townsAwarded: 12,
  },
  {
    code: "MD",
    name: "Maryland",
    grantAmount: 178132,
    townsAwarded: 5,
  },
  {
    code: "MA",
    name: "Massachusetts",
    grantAmount: 215475,
    townsAwarded: 5,
  },
  {
    code: "MI",
    name: "Michigan",
    grantAmount: 247400,
    townsAwarded: 5,
  },
  {
    code: "MN",
    name: "Minnesota",
    grantAmount: 418173,
    townsAwarded: 5,
  },
  {
    code: "MS",
    name: "Mississippi",
    grantAmount: 686294.07,
    townsAwarded: 14,
  },
  {
    code: "MO",
    name: "Missouri",
    grantAmount: 466556,
    townsAwarded: 12,
  },
  {
    code: "MT",
    name: "Montana",
    grantAmount: 279351.86,
    townsAwarded: 6,
  },
  {
    code: "NE",
    name: "Nebraska",
    grantAmount: 150000.0,
    townsAwarded: 3,
  },
  {
    code: "NV",
    name: "Nevada",
    grantAmount: 185000,
    townsAwarded: 4,
  },
  {
    code: "NH",
    name: "New Hampshire",
    grantAmount: 250000.0,
    townsAwarded: 5,
  },
  {
    code: "NJ",
    name: "New Jersey",
    grantAmount: 354121.31,
    townsAwarded: 8,
  },
  {
    code: "NM",
    name: "New Mexico",
    grantAmount: 398010.0,
    townsAwarded: 9,
  },
  {
    code: "NY",
    name: "New York",
    grantAmount: 379103,
    townsAwarded: 9,
  },
  {
    code: "NC",
    name: "North Carolina",
    grantAmount: 1054769.8,
    townsAwarded: 25,
  },
  {
    code: "ND",
    name: "North Dakota",
    grantAmount: 0,
    townsAwarded: 0,
  },
  {
    code: "OH",
    name: "Ohio",
    grantAmount: 300340,
    townsAwarded: 7,
  },
  {
    code: "OK",
    name: "Oklahoma",
    grantAmount: 712862.67,
    townsAwarded: 15,
  },
  {
    code: "OR",
    name: "Oregon",
    grantAmount: 708040,
    townsAwarded: 17,
  },
  {
    code: "PA",
    name: "Pennsylvania",
    grantAmount: 1038677.28,
    townsAwarded: 24,
  },
  {
    code: "RI",
    name: "Rhode Island",
    grantAmount: 79600.0,
    townsAwarded: 2,
  },
  {
    code: "SC",
    name: "South Carolina",
    grantAmount: 409695.0,
    townsAwarded: 9,
  },
  {
    code: "SD",
    name: "South Dakota",
    grantAmount: 0,
    townsAwarded: 0,
  },
  {
    code: "TN",
    name: "Tennessee",
    grantAmount: 453655.81,
    townsAwarded: 10,
  },
  {
    code: "TX",
    name: "Texas",
    grantAmount: 818187.1,
    townsAwarded: 18,
  },
  {
    code: "UT",
    name: "Utah",
    grantAmount: 294000.0,
    townsAwarded: 6,
  },
  {
    code: "VT",
    name: "Vermont",
    grantAmount: 150000.0,
    townsAwarded: 3,
  },
  {
    code: "VA",
    name: "Virginia",
    grantAmount: 409011.0,
    townsAwarded: 9,
  },
  {
    code: "WA",
    name: "Washington",
    grantAmount: 752802.7,
    townsAwarded: 16,
  },
  {
    code: "WV",
    name: "West Virginia",
    grantAmount: 306256.0,
    townsAwarded: 7,
  },
  {
    code: "WI",
    name: "Wisconsin",
    grantAmount: 522845.0,
    townsAwarded: 12,
  },
  {
    code: "WY",
    name: "Wyoming",
    grantAmount: 150000.0,
    townsAwarded: 3,
  },
];
