const stateData = [
  {
    code: "AL",
    name: "Alabama",
    grantAmount: 843050,
    townsAwarded: 16,
    towns: [
      "Atmore",
      "Attalla",
      "Childersburg",
      "City of Northport",
      "City of Selma",
      "Fairfield",
      "Jacksonville",
      "Leeds",
      "Montevallo",
      "Prattville",
      "Prichard",
      "Saraland",
      "Springville",
      "Talladega",
      "Wedowee",
      "Wetumpka",
    ],
  },
  {
    code: "AK",
    name: "Alaska",
    grantAmount: 0,
    townsAwarded: 0,
  },
  {
    code: "AZ",
    name: "Arizona",
    grantAmount: 331285,
    townsAwarded: 6,
    towns: ["Clarkdale", "Safford", "Superior", "Wickenburg"],
  },
  {
    code: "AR",
    name: "Arkansas",
    grantAmount: 426000,
    townsAwarded: 9,
    towns: ["Chino Valley", "Camden", "Clarksville", "Osceola", "Ozark", "Paris", "Russellville", "Sheridan"],
  },
  {
    code: "CA",
    name: "California",
    grantAmount: 968286.98,
    townsAwarded: 20,
    towns: [
      "Calexico",
      "Coalinga",
      "Eureka",
      "Farmersville",
      "Fort Bragg",
      "Heber",
      "King City",
      "Kingsburg",
      "Mammoth Lakes",
      "Mt. Shasta",
      "Needles",
      "Orosi",
      "Paradise",
      "Placerville",
      "Reedley",
      "Rohnert Park",
      "Soledad",
      "South Lake Tahoe",
      "Ukiah",
      "Yreka",
    ],
  },
  {
    code: "CO",
    name: "Colorado",
    grantAmount: 153000,
    townsAwarded: 4,
    towns: ["Evergreen", "Montrose", "Paonia", "Strasburg"],
  },
  {
    code: "CT",
    name: "Connecticut",
    grantAmount: 124192,
    townsAwarded: 3,
    towns: ["Franklin", "Mashantucket Pequot Tribal Nation", "Newtown"],
  },
  {
    code: "DE",
    name: "Delaware",
    grantAmount: 79250,
    townsAwarded: 2,
    towns: ["Milford,", "Smyrna"],
  },
  {
    code: "DC",
    name: "District Of Columbia",
    grantAmount: 0,
    townsAwarded: 0,
  },
  {
    code: "FL",
    name: "Florida",
    grantAmount: 412723,
    townsAwarded: 9,
    towns: [
      "Alachua",
      "City of Lake Wales",
      "Fernandina Beach",
      "Fort Pierce",
      "Lake Placid",
      "Monticello",
      "Okeechobee",
      "Quincy",
      "Aradia",
    ],
  },
  {
    code: "GA",
    name: "Georgia",
    grantAmount: 749174,
    townsAwarded: 15,
    towns: [
      "Calhoun",
      "Cedartown",
      "Comer",
      "Cordele",
      "Darien",
      "Eastman",
      "Fort Valley",
      "Hogansville",
      "Kennesaw",
      "Manchester",
      "Milledgeville",
      "Mt. Airy",
      "Thomasville",
      "Tybee Island",
      "Woodbine",
    ],
  },
  {
    code: "HI",
    name: "Hawaii",
    grantAmount: 50000,
    townsAwarded: 1,
    towns: ["Kunia Village"],
  },
  {
    code: "ID",
    name: "Idaho",
    grantAmount: 308496,
    townsAwarded: 6,
    towns: ["Bonners Ferry", "Burley", "Fairfield", "Fruitland", "Rexburg", "Salmon"],
  },
  {
    code: "IL",
    name: "Illinois",
    grantAmount: 846855.81,
    townsAwarded: 19,
    towns: [
      "Carbondale",
      "City of DeKalb",
      "Crystal Lake",
      "Dixon",
      "Effingham",
      "Freeport",
      "Galesburg",
      "Hoopeston",
      "Kankakee",
      "Mattoon",
      "Moline",
      "Mt. Vernon",
      "Plainfield",
      "Rock Island",
      "Sterling",
      "Sycamore",
      "Highland",
      "Paxton",
      "Rantoul",
    ],
  },
  {
    code: "IN",
    name: "Indiana",
    grantAmount: 474967.0,
    townsAwarded: 10,
    towns: [
      "Angola",
      "Argos",
      "Batesville",
      "Columbia City",
      "Covington",
      "Kendallville",
      "Madison",
      "North Manchester",
      "Peru",
      "Versailles",
    ],
  },
  {
    code: "IA",
    name: "Iowa",
    grantAmount: 655975.5,
    townsAwarded: 15,
    towns: [
      "Adel",
      "City of Marshalltown",
      "Clinton",
      "Colfax",
      "Eldora",
      "Fairfield",
      "Independence",
      "Keokuk",
      "Lansing",
      "Mason City",
      "Mount Vernon",
      "Peosta",
      "Perry",
      "Spencer",
      "Storm Lake",
    ],
  },
  {
    code: "KS",
    name: "Kansas",
    grantAmount: 623500,
    townsAwarded: 13,
    towns: [
      "Auburn",
      "Augusta",
      "El Dorado",
      "Fort Scott",
      "Gardner",
      "Hutchinson",
      "Iola",
      "Junction City",
      "Ottawa",
      "Parsons",
      "Winfield",
      "Yates Center",
    ],
  },
  {
    code: "KY",
    name: "Kentucky",
    grantAmount: 479768.3,
    townsAwarded: 11,
    towns: [
      "Berea",
      "City of West Point",
      "Columbia",
      "Grayson",
      "Henderson",
      "Murray",
      "Pineville",
      "Prestonsburg",
      "Princeton",
      "Richmond",
      "Taylorsville",
    ],
  },
  {
    code: "LA",
    name: "Louisiana",
    grantAmount: 250000.0,
    townsAwarded: 5,
    towns: ["Hammond", "Natchitoches", "Ruston", "Slidell", "West Monroe "],
  },
  {
    code: "ME",
    name: "Maine",
    grantAmount: 526072,
    townsAwarded: 12,
    towns: [
      "Augusta",
      "Bangor",
      "Brunswick",
      "Castine",
      "Ellsworth",
      "Freeport",
      "Pittsfield",
      "Saco",
      "Searsmont",
      "Skowhegan",
      "Yarmouth",
    ],
  },
  {
    code: "MD",
    name: "Maryland",
    grantAmount: 178132,
    townsAwarded: 5,
    towns: ["Brunswick", "Cambridge", "Cumberland", "Easton", "Hagerstown"],
  },
  {
    code: "MA",
    name: "Massachusetts",
    grantAmount: 215475,
    townsAwarded: 5,
    towns: ["Gloucester", "Great Barrington", "Kingston", "Northampton", "Winchendon"],
  },
  {
    code: "MI",
    name: "Michigan",
    grantAmount: 247400,
    townsAwarded: 5,
    towns: ["Chelsea", "Lake Orion", "Marine City", "Oxford", "Three Rivers"],
  },
  {
    code: "MN",
    name: "Minnesota",
    grantAmount: 468473,
    townsAwarded: 10,
    towns: [
      "City of Howard Lake",
      "Crookston",
      "Detroit Lakes",
      "Granite Falls",
      "Mapleton",
      "Marshall",
      "Owatonna",
      "Red Wing",
      "Scandia",
      "Silver Bay",
    ],
  },
  {
    code: "MS",
    name: "Mississippi",
    grantAmount: 786294.07,
    townsAwarded: 14,
    towns: [
      "Clarksdale",
      "Corinth",
      "Drew",
      "Greenville",
      "Hattiesburg",
      "Hazlehurst",
      "Laurel",
      "Magee",
      "McComb",
      "Mendenhall",
      "Nettleton",
      "Oxford",
      "Tupelo",
      "West Point",
    ],
  },
  {
    code: "MO",
    name: "Missouri",
    grantAmount: 466556,
    townsAwarded: 12,
    towns: [
      "Cape Girardeau",
      "Chillicothe",
      "Excelsior Springs",
      "Harrisonville",
      "Holden",
      "Kirksville",
      "Nixa",
      "Pineville",
      "Poplar Bluff",
      "Rolla",
      "Webb City",
      "Hannibal",
    ],
  },
  {
    code: "MT",
    name: "Montana",
    grantAmount: 279351.86,
    townsAwarded: 6,
    towns: ["Absarokee", "Choteau", "Evergreen", "Glasgow", "Laurel", "White Sulphur Springs"],
  },
  {
    code: "NE",
    name: "Nebraska",
    grantAmount: 150000.0,
    townsAwarded: 3,
    towns: ["Columbus", "Hartington", "Norfolk"],
  },
  {
    code: "NV",
    name: "Nevada",
    grantAmount: 185000,
    townsAwarded: 4,
    towns: ["Lovelock", "Minden", "Pahrump", "Searchlight "],
  },
  {
    code: "NH",
    name: "New Hampshire",
    grantAmount: 300000.0,
    townsAwarded: 6,
    towns: ["Claremont", "Goffstown", "Keene", "Lebanon", "Peterborough", "Sanbornton"],
  },
  {
    code: "NJ",
    name: "New Jersey",
    grantAmount: 354121.31,
    townsAwarded: 8,
    towns: ["Allentown", "Bound Brook", "Bridgeton", "Burlington", "Dover", "Hillsborough", "Stanhope", "Washington"],
  },
  {
    code: "NM",
    name: "New Mexico",
    grantAmount: 498010.0,
    townsAwarded: 11,
    towns: [
      "Carlsbad",
      "Clovis",
      "Doña Ana",
      "Espanola",
      "Farmington",
      "Grants",
      "Las Vegas",
      "Los Alamos",
      "Lovington",
      "Raton",
      "Taos",
    ],
  },
  {
    code: "NY",
    name: "New York",
    grantAmount: 379103,
    townsAwarded: 9,
    towns: [
      "Akwesasne",
      "Bath",
      "Elmira",
      "Ithaca",
      "Liberty",
      "Otisville",
      "Potsdam",
      "Town of Poughkeepsie",
      "Village of Arcade",
    ],
  },
  {
    code: "NC",
    name: "North Carolina",
    grantAmount: 961800.5,
    townsAwarded: 22,
    towns: [
      "Aberdeen",
      "Boiling Springs",
      "Cullowhee",
      "Edenton",
      "Elizabeth City",
      "Elizabethtown",
      "Gold Hill",
      "Goldsboro",
      "Henderson",
      "Hickory",
      "Hickory",
      "Kings Mountain",
      "Laurinburg",
      "Laurinburg",
      "Mars Hill",
      "Marshall",
      "Morven",
      "Mount Airy",
      "Murphy",
      "North Wilkesboro",
      "Pilot Mountain",
      "Robersonville",
      "Town of Princeville",
      "Wilkesboro",
    ],
  },
  {
    code: "ND",
    name: "North Dakota",
    grantAmount: 50000,
    townsAwarded: 1,
    towns: ["Mandan"],
  },
  {
    code: "OH",
    name: "Ohio",
    grantAmount: 350340,
    townsAwarded: 8,
    towns: ["Bowling Green", "Columbiana", "Decatur", "Lima", "Salem", "Wooster", "Chillicothe", "Wapakoneta "],
  },
  {
    code: "OK",
    name: "Oklahoma",
    grantAmount: 712862.67,
    townsAwarded: 15,
    towns: [
      "Ada",
      "Altus",
      "Anadarko",
      "Durant",
      "El Reno",
      "Grove",
      "Guthrie",
      "Guymon",
      "Kansas",
      "Perkins",
      "Ponca City",
      "Poteau",
      "Sallisaw",
      "Shawnee",
    ],
  },
  {
    code: "OR",
    name: "Oregon",
    grantAmount: 758040,
    townsAwarded: 18,
    towns: [
      "Ashland",
      "Aumsville",
      "Baker City",
      "Cottage Grove",
      "Independence",
      "Jefferson",
      "Lebanon",
      "Madras",
      "McMinnville",
      "Monmouth",
      "North Bend",
      "Phoenix",
      "Siletz",
      "Silverton",
      "Talent",
      "The Dalles",
      "Toledo",
      "Warm Springs",
    ],
  },
  {
    code: "PA",
    name: "Pennsylvania",
    grantAmount: 1122690.17,
    townsAwarded: 25,
    towns: [
      "Beaver Falls",
      "Bradford",
      "City of Aliquippa",
      "City of Oil City",
      "Coatesville",
      "Coopersburg",
      "DuBois",
      "Easton",
      "Elizabeth",
      "Hamburg",
      "Hatboro Borough",
      "Herminie",
      "Hershey",
      "Johnstown",
      "Kutztown",
      "Lewistown",
      "Lock Haven",
      "Meadville",
      "Mechanicsburg",
      "Phoenixville",
      "Pittston",
      "South Fayette Township",
      "Stroudsburg",
      "York",
    ],
  },
  {
    code: "PR",
    name: "Puerto Rico",
    grantAmount: 50000,
    townsAwarded: 1,
    towns: ["Aguas Buenas"],
  },
  {
    code: "RI",
    name: "Rhode Island",
    grantAmount: 79600.0,
    townsAwarded: 2,
    towns: ["Bristol", "Saunderstown "],
  },
  {
    code: "SC",
    name: "South Carolina",
    grantAmount: 409695,
    townsAwarded: 9,
    towns: [
      "Abbeville",
      "Florence",
      "Hanahan",
      "Kingstree",
      "Marion",
      "Myrtle Beach",
      "Pendleton",
      "Port Royal",
      "St. Stephen",
    ],
  },
  {
    code: "SD",
    name: "South Dakota",
    grantAmount: 50000,
    townsAwarded: 1,
    towns: ["Canton"],
  },
  {
    code: "TN",
    name: "Tennessee",
    grantAmount: 520163.51,
    townsAwarded: 12,
    towns: [
      "Bristol",
      "Brownsville",
      "Cleveland",
      "Dyersburg",
      "Erwin",
      "Jasper",
      "Lawrenceburg",
      "Loudon",
      "Mooresburg",
      "Mount Carmel",
      "Shelbyville",
    ],
  },
  {
    code: "TX",
    name: "Texas",
    grantAmount: 868187.1,
    townsAwarded: 19,
    towns: [
      "Brackettville",
      "City of Falfurrias",
      "City of Robstown",
      "Cleveland",
      "Dale",
      "Elgin",
      "Giddings",
      "Hearne",
      "La Grange",
      "Levelland",
      "Los Fresnos",
      "Mineral Wells",
      "Palmview",
      "Plainview",
      "Rice",
      "Rio Grande City",
      "Sabinal",
      "South Padre Island",
      "Zapata",
    ],
  },
  {
    code: "UT",
    name: "Utah",
    grantAmount: 294000,
    townsAwarded: 6,
    towns: ["Ephraim", "Helper City", "Hurricane", "Payson", "Springville", "Vernal "],
  },
  {
    code: "VT",
    name: "Vermont",
    grantAmount: 182900,
    townsAwarded: 3,
    towns: ["Brattleboro", "Burlington", "Charlotte"],
  },
  {
    code: "VA",
    name: "Virginia",
    grantAmount: 450705,
    townsAwarded: 9,
    towns: [
      "Bristol",
      "Danville",
      "Luray",
      "New Castle",
      "Rocky Mount",
      "Smithfield",
      "Staunton",
      "Stuart",
      "Waynesboro",
    ],
  },
  {
    code: "WA",
    name: "Washington",
    grantAmount: 799897.7,
    townsAwarded: 17,
    towns: [
      "Bremerton",
      "Clarkston",
      "College Place",
      "Cosmopolis",
      "Enumclaw",
      "Ferndale",
      "Langley",
      "Mesa",
      "Moses Lake",
      "Newport",
      "Oak Harbor",
      "Shelton",
      "Stanwood",
      "Toppenish",
      "Vashon",
      "Colville",
      "Pullman",
    ],
  },
  {
    code: "WV",
    name: "West Virginia",
    grantAmount: 306256,
    townsAwarded: 7,
    towns: ["Charleston", "Fayetteville", "Huntington", "Kingwood", "Madison", "Saint Albans "],
  },
  {
    code: "WI",
    name: "Wisconsin",
    grantAmount: 640645,
    townsAwarded: 15,
    towns: [
      "Amery",
      "Chippewa Falls",
      "City of Waupaca",
      "New Richmond",
      "Osceola",
      "Manitowoc",
      "Rice Lake",
      "River Falls",
      "Sun Prairie",
      "Two Rivers",
      "Village of Kimberly",
      "Village of Wausaukee",
      "Viroqua",
      "Wausau",
      "West Bend",
    ],
  },
  {
    code: "WY",
    name: "Wyoming",
    grantAmount: 150000,
    townsAwarded: 3,
    towns: ["Cody", "Lander", "Sheridan"],
  },
];
