const highSchoolData = [
  {
    id: 0,
    name: "Generic H.S.",
    city: "Stufftown",
    state: "WA",
    region: "West",
    votes: 22000,
  },
  {
    id: 1,
    name: "Bigtime H.S.",
    city: "Gadgetville",
    state: "WA",
    region: "West",
    votes: 14283,
  },
  {
    id: 2,
    name: "Badass H.S.",
    city: "Itemburg",
    state: "WA",
    region: "West",
    votes: 17091,
  },
  {
    id: 3,
    name: "Standard H.S.",
    city: "Thing Creek",
    state: "WA",
    region: "West",
    votes: 10542,
  },
  {
    id: 4,
    name: "Typical H.S.",
    city: "Object City",
    state: "WA",
    region: "West",
    votes: 13219,
  },
  {
    id: 5,
    name: "Ordinary H.S.",
    city: "Article Junction",
    state: "WA",
    region: "West",
    votes: 9115,
  },
  {
    id: 6,
    name: "Common H.S.",
    city: "Material Falls",
    state: "WA",
    region: "West",
    votes: 12480,
  },
  {
    id: 7,
    name: "Mediocre H.S.",
    city: "Entity Springs",
    state: "WA",
    region: "West",
    votes: 14722,
  },
  {
    id: 8,
    name: "Regular H.S.",
    city: "Unit Village",
    state: "WA",
    region: "West",
    votes: 8933,
  },
  {
    id: 9,
    name: "Normal H.S.",
    city: "Piece Port",
    state: "WA",
    region: "West",
    votes: 11674,
  },
  {
    id: 10,
    name: "Dude H.S.",
    city: "Spiffytown",
    state: "MA",
    region: "East",
    votes: 12000,
  },
  {
    id: 11,
    name: "Spectacular H.S.",
    city: "Dapperburg",
    state: "MA",
    region: "East",
    votes: 14283,
  },
  {
    id: 12,
    name: "Awesome H.S.",
    city: "Snazzyville",
    state: "MA",
    region: "East",
    votes: 13091,
  },
  {
    id: 13,
    name: "Radical H.S.",
    city: "Posh Point",
    state: "MA",
    region: "East",
    votes: 9821,
  },
  {
    id: 14,
    name: "Excellent H.S.",
    city: "Nifty Heights",
    state: "MA",
    region: "East",
    votes: 12554,
  },
  {
    id: 15,
    name: "Tubular H.S.",
    city: "Classy Corner",
    state: "MA",
    region: "East",
    votes: 14109,
  },
  {
    id: 16,
    name: "Killer H.S.",
    city: "Swell Side",
    state: "MA",
    region: "East",
    votes: 8945,
  },
  {
    id: 17,
    name: "Gnarly H.S.",
    city: "Flashy Field",
    state: "MA",
    region: "East",
    votes: 13202,
  },
  {
    id: 18,
    name: "Superb H.S.",
    city: "Polished Park",
    state: "MA",
    region: "East",
    votes: 10776,
  },
  {
    id: 19,
    name: "Choice H.S.",
    city: "Chic Center",
    state: "MA",
    region: "East",
    votes: 12891,
  },
  {
    id: 20,
    name: "Dude H.S.",
    city: "Rockintown",
    state: "MI",
    region: "Midwest",
    votes: 14000,
  },
  {
    id: 21,
    name: "Sassy H.S.",
    city: "Jammingville",
    state: "MI",
    region: "Midwest",
    votes: 14283,
  },
  {
    id: 22,
    name: "Awesome H.S.",
    city: "Grooveburg",
    state: "MI",
    region: "Midwest",
    votes: 13091,
  },
  {
    id: 23,
    name: "Wicked H.S.",
    city: "Vibe Valley",
    state: "MI",
    region: "Midwest",
    votes: 11443,
  },
  {
    id: 24,
    name: "Prime H.S.",
    city: "Stellar Station",
    state: "MI",
    region: "Midwest",
    votes: 14605,
  },
  {
    id: 25,
    name: "Phat H.S.",
    city: "Bumping Bend",
    state: "MI",
    region: "Midwest",
    votes: 9231,
  },
  {
    id: 26,
    name: "Top-Tier H.S.",
    city: "Lively Lane",
    state: "MI",
    region: "Midwest",
    votes: 12988,
  },
  {
    id: 27,
    name: "Epic H.S.",
    city: "Electric Edge",
    state: "MI",
    region: "Midwest",
    votes: 10114,
  },
  {
    id: 28,
    name: "Classic H.S.",
    city: "Beating Bridge",
    state: "MI",
    region: "Midwest",
    votes: 13540,
  },
  {
    id: 29,
    name: "Solid H.S.",
    city: "Active Acres",
    state: "MI",
    region: "Midwest",
    votes: 11002,
  },
  {
    id: 30,
    name: "Dude H.S.",
    city: "Neatotown",
    state: "GA",
    region: "South",
    votes: 12000,
  },
  {
    id: 31,
    name: "Groovy H.S.",
    city: "Tidyton",
    state: "GA",
    region: "South",
    votes: 14283,
  },
  {
    id: 32,
    name: "Awesome H.S.",
    city: "Cleanville",
    state: "GA",
    region: "South",
    votes: 13091,
  },
  {
    id: 33,
    name: "Neat H.S.",
    city: "Trim Terrace",
    state: "GA",
    region: "South",
    votes: 14339,
  },
  {
    id: 34,
    name: "Fly H.S.",
    city: "Orderly Oasis",
    state: "GA",
    region: "South",
    votes: 11506,
  },
  {
    id: 35,
    name: "Sharp H.S.",
    city: "Smart Shore",
    state: "GA",
    region: "South",
    votes: 9422,
  },
  {
    id: 36,
    name: "Dope H.S.",
    city: "Spruce Summit",
    state: "GA",
    region: "South",
    votes: 12117,
  },
  {
    id: 37,
    name: "Swell H.S.",
    city: "Crisp Canyon",
    state: "GA",
    region: "South",
    votes: 13785,
  },
  {
    id: 38,
    name: "Boss H.S.",
    city: "Fresh Forest",
    state: "GA",
    region: "South",
    votes: 10459,
  },
  {
    id: 39,
    name: "Grand H.S.",
    city: "Prim Plains",
    state: "GA",
    region: "South",
    votes: 11890,
  },
];
