const highSchoolData = {
  highSchools: [
    {
      id: "0",
      name: "Generic H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 22000,
    },
    {
      id: "1",
      name: "Bigtime H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 14283,
    },
    {
      id: "2",
      name: "Badass H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 17091,
    },
    {
      id: "3",
      name: "Average H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 11826,
    },
    {
      id: "4",
      name: "Average H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 11826,
    },
    {
      id: "5",
      name: "Average H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 11826,
    },
    {
      id: "6",
      name: "Average H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 11826,
    },
    {
      id: "7",
      name: "Dude H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 12000,
    },
    {
      id: "8",
      name: "Spectacular H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 14283,
    },
    {
      id: "9",
      name: "Awesome H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 13091,
    },
    {
      id: "10",
      name: "Sweet H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 11826,
    },
    {
      id: "11",
      name: "Sweet H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 11826,
    },
    {
      id: "12",
      name: "Sweet H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 11826,
    },
    {
      id: "13",
      name: "Sweet H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 11826,
    },
    {
      id: "14",
      name: "Dude H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 14000,
    },
    {
      id: "15",
      name: "Sassy H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 14283,
    },
    {
      id: "16",
      name: "Awesome H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 13091,
    },
    {
      id: "17",
      name: "Sweet H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 11826,
    },
    {
      id: "18",
      name: "Sweet H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 11826,
    },
    {
      id: "19",
      name: "Sweet H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 11826,
    },
    {
      id: "20",
      name: "Sweet H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 11826,
    },
    {
      id: "21",
      name: "Dude H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 12000,
    },
    {
      id: "22",
      name: "Groovy H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 14283,
    },
    {
      id: "23",
      name: "Awesome H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 13091,
    },
    {
      id: "24",
      name: "Sweet H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 11826,
    },
    {
      id: "25",
      name: "Sweet H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 11826,
    },
    {
      id: "26",
      name: "Sweet H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 11826,
    },
    {
      id: "27",
      name: "Sweet H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 11826,
    },
  ],
};

const highSchoolDataPrevious = {
  highSchoolsPrevious: [
    {
      id: "0",
      name: "Generic H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 22000,
    },
    {
      id: "1",
      name: "Bigtime H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 14283,
    },
    {
      id: "2",
      name: "Badass H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 17091,
    },
    {
      id: "3",
      name: "Average H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 11826,
    },
    {
      id: "4",
      name: "Average H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 11826,
    },
    {
      id: "5",
      name: "Average H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 11826,
    },
    {
      id: "6",
      name: "Average H.S.",
      city: "Stufftown",
      state: "WA",
      region: "west",
      votes: 11826,
    },
    {
      id: "7",
      name: "Dude H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 12000,
    },
    {
      id: "8",
      name: "Spectacular H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 14283,
    },
    {
      id: "9",
      name: "Awesome H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 13091,
    },
    {
      id: "10",
      name: "Sweet H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 11826,
    },
    {
      id: "11",
      name: "Sweet H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 11826,
    },
    {
      id: "12",
      name: "Sweet H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 11826,
    },
    {
      id: "13",
      name: "Sweet H.S.",
      city: "Spiffytown",
      state: "MA",
      region: "east",
      votes: 11826,
    },
    {
      id: "14",
      name: "Dude H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 14000,
    },
    {
      id: "15",
      name: "Sassy H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 14283,
    },
    {
      id: "16",
      name: "Awesome H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 13091,
    },
    {
      id: "17",
      name: "Sweet H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 11826,
    },
    {
      id: "18",
      name: "Sweet H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 11826,
    },
    {
      id: "19",
      name: "Sweet H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 11826,
    },
    {
      id: "20",
      name: "Sweet H.S.",
      city: "Rockintown",
      state: "MI",
      region: "north",
      votes: 11826,
    },
    {
      id: "21",
      name: "Dude H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 12000,
    },
    {
      id: "22",
      name: "Groovy H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 14283,
    },
    {
      id: "23",
      name: "Awesome H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 13091,
    },
    {
      id: "24",
      name: "Sweet H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 11826,
    },
    {
      id: "25",
      name: "Sweet H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 11826,
    },
    {
      id: "26",
      name: "Sweet H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 11826,
    },
    {
      id: "27",
      name: "Sweet H.S.",
      city: "Neatotown",
      state: "GA",
      region: "south",
      votes: 11826,
    },
  ],
};
